### Intro to Numpy

#### Agenda:
 
    * How to import an umpire library first how to create an array.
    
    * Basic Operation on numpy array
    
    * How to use the shape function. 

We'll deal more in depth and in detail with all uses of these very useful and fundamental library.

---

In [1]:
#Import Library

import numpy as np

### Python's List

In [2]:
# Create a list
# Add plus 1 to the elements of the list
# typeerror (list and int)

arr_1 = [1,2,3,4,5,6]

arr_1 +=1

TypeError: 'int' object is not iterable

In [3]:
type(arr_1)

list

> with regular list, we weren't able to add an integer 1 to each element on the array. Is is not possible.

---

### With Numpy Array

In [4]:
# Create a numpy array

arr_2 = np.array([1,2,3,4,5,6])

type(arr_2)

numpy.ndarray

In [5]:
# Now we add again a new element using numpy arrays

arr_2 +=1

arr_2

array([2, 3, 4, 5, 6, 7])

> Now, with numpy array, we were able to add an integer 1 to each element on the list

In [6]:
# Adding each element in numpy array

arr_3 = arr_2 + 1

arr_3

array([3, 4, 5, 6, 7, 8])

In [7]:
# Adding numpy arrays with equal elements

arr_2 + arr_3

array([ 5,  7,  9, 11, 13, 15])

In [8]:
# Accessging individual elements

arr_2[0]

2

In [9]:
# slicing elements from numpy array

arr_2[1:]

array([3, 4, 5, 6, 7])

In [10]:
# Declare new numpy array

arr_4 = np.array([2,3,4])

In [11]:
# Adding numping arrays with not equal number of elements

arr_2 + arr_4

ValueError: operands could not be broadcast together with shapes (6,) (3,) 

In [12]:
# Get the Shape

arr_2.shape, arr_4.shape

((6,), (3,))

In [13]:
# Create a 2 dimensional array

arr_5 = np.array([['1','2','3'],
                ['a','b','c']])

arr_5

array([['1', '2', '3'],
       ['a', 'b', 'c']], dtype='<U1')