### Intro to Numpy

#### Agenda:
 
    * Numpy fundamentals.
    
        - Creating Numpy array from Python list.
        
        - Type and Dtype function
        
        - Implicit Parsing of data types
        
            - Int, float, unicode/character string
            
        - Size, Shape, and Ndim Functions
        
        - Fill Function
        
        
    
    

---

In [1]:
#Import Library

import numpy as np

### Python's List

In [2]:
# Create a Python list
# Create a numpy array from the python list

list1 = [1,2,3,4,5]
arr_1 = np.array(list1)

arr_1

array([1, 2, 3, 4, 5])

In [3]:
# Type of the container

type(arr_1)

numpy.ndarray

In [4]:
# type data of the element inside of the container

arr_1.dtype

dtype('int64')

---

#### Add a Float dtype

In [5]:
# Append 6.0 on the list

list1.append(6.0)
list1

[1, 2, 3, 4, 5, 6.0]

In [7]:
# Create again a numpy array from the updated pyhton list

arr_2 = np.array(list1)
arr_2

array([1., 2., 3., 4., 5., 6.])

In [8]:
# Type of the container - same container datatype

type(arr_2)

numpy.ndarray

In [9]:
# Every element now is of type float after adding 6.0 to the list

arr_2.dtype

dtype('float64')

---

#### Add a String dtype

In [10]:
# Append 6.0 on the list

list1.append('string')
list1

[1, 2, 3, 4, 5, 6.0, 'string']

In [11]:
# Create again a numpy array from the updated pyhton list

arr_3 = np.array(list1)
arr_3

array(['1', '2', '3', '4', '5', '6.0', 'string'], dtype='<U32')

In [12]:
# Type of the container - same container datatype

type(arr_3)

numpy.ndarray

In [13]:
# Every element now is of type unicode after adding string to the list
# Indiates 32-Characters String type on this array

arr_3.dtype

dtype('<U32')

---

#### Size Function, Shape Function, Ndim Function

In [15]:
# Size Function to see the number of elements

arr_1.size

5

In [16]:
# with shape, you can also see the array dimension and is much more usefull as it gives you more information

arr_1.shape

(5,)

In [17]:
# Another way of getting the shape of the array

np.shape(arr_1)

(5,)

In [18]:
# to see the dimension

np.ndim(arr_1)

1

In [20]:
# Another way to see the dimension

arr_1.ndim

1

---

#### Fill Function

In [21]:
# Now lets see the values of arr_1

arr_1

array([1, 2, 3, 4, 5])

In [23]:
# Let's fill the array with value = 3

arr_1.fill(3)

arr_1

array([3, 3, 3, 3, 3])