### Matrix

#### Agenda:
 
    * Matrix fundamentals.
  
        
        - 2 dimensional Array is a Matrix.
        

     * Indexing

---

In [1]:
#Import Library

import numpy as np

In [2]:
# Create a 2 dimensional array - Matrix

m1 = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
# Dimenion of the matrix

m1.shape

(3, 3)

In [4]:
# Total Number of elements
m1.size

9

In [6]:
# Total Number of dimesnion

m1.ndim

2

---

#### Indexing

In [8]:
# Get the element 6

m1[1,2]

6

In [9]:
# Element Value Reassignment

m1[1,2] = 16
m1

array([[ 1,  2,  3],
       [ 4,  5, 16],
       [ 7,  8,  9]])

In [12]:
# Get the entire values of the last row for m1

m1[2]

array([7, 8, 9])

In [15]:
# Get the entire values of the last column for m1

m1[:,2]

array([ 3, 16,  9])

In [18]:
# Get the first two elements on the second row/line of m1

m1[1,0:2]

array([4, 5])