### Mathematical Functions

#### Agenda:
 
    * sum()
    
    * axis parameter (0 -vertical, 1 -horizontal)
    
    * Min, Max, Mean, Standard Deviation, Variation
    
    * argmin, argmax
    
    * clip
    
    * round
  
        

---

In [1]:
#Import Library

import numpy as np

In [3]:
# Create a 2 dimensional array - Matrix

n1 = np.array([[1,2,3,4],
               [5,6,7,8]],
              dtype = np.float32)

n1

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]], dtype=float32)

---

#### Sum

In [4]:
# sum of all the elements in the matrix

n1.sum()

36.0

In [5]:
# sum of all the elements in the matrix

np.sum(n1)

36.0

> Not really useful in data analysis

In [8]:
# Specify the axis to that the summation vertically

np.sum(n1, axis=1)

array([10., 26.], dtype=float32)

> Now, we can use the sum or total across horizontally.

In [7]:
# Specify the axis to that the summation horizontally

np.sum(n1, axis=0)

array([ 6.,  8., 10., 12.], dtype=float32)

---

#### Product

In [9]:
# Results in multiple all the elements in the matrix

n1.prod()

40320.0

In [11]:
# Product of the list
# Product is equal to multiplying the list

n1.prod(axis=0)

array([ 5., 12., 21., 32.], dtype=float32)

In [12]:
# Product of the elements
# Product is equal to multiplying across the elements per list

n1.prod(axis=1)

array([  24., 1680.], dtype=float32)

---

#### Min

In [13]:
n1.min()

1.0

In [14]:
# axis = 0

n1.min(axis=0)

array([1., 2., 3., 4.], dtype=float32)

In [16]:
# axis = 1

n1.min(axis=1)

array([1., 5.], dtype=float32)

---

In [17]:
n1.max()

8.0

In [18]:
# axis = 0

n1.max(axis=0)

array([5., 6., 7., 8.], dtype=float32)

In [19]:
# axis = 1

n1.max(axis=1)

array([4., 8.], dtype=float32)

---

#### Argmin - minimum value of the list

In [20]:
n1.argmin()

0

In [21]:
# axis = 0

n1.argmin(axis=0)

array([0, 0, 0, 0])

In [22]:
# axis = 1

n1.argmin(axis=1)

array([0, 0])

#### Argmax - maximum value of the list

In [23]:
n1.argmax()

7

In [24]:
# axis = 0

n1.argmax(axis=0)

array([1, 1, 1, 1])

In [25]:
# axis = 1

n1.argmax(axis=1)

array([3, 3])

---

In [27]:
n1.mean()

4.5

In [28]:
# axis = 0

n1.mean(axis=0)

array([3., 4., 5., 6.], dtype=float32)

In [29]:
# axis = 1

n1.mean(axis=1)

array([2.5, 6.5], dtype=float32)

---

#### Standard Deviation

In [31]:
n1.std()

2.291288

In [32]:
# axis = 0

n1.std(axis=0)

array([2., 2., 2., 2.], dtype=float32)

In [33]:
# axis = 1

n1.std(axis=1)

array([1.118034, 1.118034], dtype=float32)

---

#### Simple Variance

> The simple variance is nothing more than an indicator of statistical variability that can be calculated as a set in a sample

In [34]:
n1.var()

5.25

In [35]:
# axis = 0

n1.var(axis=0)

array([4., 4., 4., 4.], dtype=float32)

In [36]:
# axis = 1

n1.var(axis=1)

array([1.25, 1.25], dtype=float32)

---

#### Clip

> This function allows us to format the values as we want.

In [37]:
n1

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]], dtype=float32)

In [38]:
# All the values less than 2 will be 2 and all the values greater than 4 will be 4.

n1.clip(2,4)

array([[2., 2., 3., 4.],
       [4., 4., 4., 4.]], dtype=float32)

In [39]:
#Create an new numpy array

n2 = np.array([4.12,5.5,6.666])
n2

array([4.12 , 5.5  , 6.666])

#### Round 

In [40]:
# Rounding the element values to 1s'

n2.round()

array([4., 6., 7.])

In [41]:
# Rounding the element values up to the second value or decimal point

n2.round(decimals=2)

array([4.12, 5.5 , 6.67])