### Data Management


---

#### Agenda:
 
   * Using **`` shape ``** function to manipulate/transform into reshaping your array
    
   * Using **`` reshape ``** function to manipulate/transform into reshaping your array
    
   * Using **`` newaxis ``** function to add dimension to an array
   
   * Using **`` squeeze ``** function to remove/delete dimension to an array
   
   * Using **`` transpose ``** function to transform into reshaping your array
   
   * Using **`` concatenate ``** function to transform into reshaping your array
   
   * Using **`` vstack ``** and **`` hstack ``** function to transform into reshaping your array
   
   * Using **`` flatten ``** function to flatten your n-dimensional array into a vector or 1 dimensional array
   
   * Using **`` ravel ``** function to flatten your n-dimensional array into a vector or 1 dimensional array
  
        

---

In [1]:
import numpy as np

#### Using Shape

In [2]:
arr_1 = np.arange(3,23,2)
arr_1

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [3]:
arr_1.shape

(10,)

In [4]:
arr_1.shape = 2,5
arr_1

array([[ 3,  5,  7,  9, 11],
       [13, 15, 17, 19, 21]])

#### Using Shape

In [5]:
arr_1.reshape(1,10)

array([[ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21]])

---

In [6]:
# Create a new array

arr_2 = np.arange(5)
arr_2

array([0, 1, 2, 3, 4])

In [7]:
# Get the shape

arr_2.shape

(5,)

---

#### Newaxis

> allows us to create a new dimension of the array

In [8]:
# Create a new dimension and copy all the elements from arr_2 as indicated by the colon (:)

arr_3 = arr_2[np.newaxis, :]
arr_3

array([[0, 1, 2, 3, 4]])

In [9]:
# Get the shape of the newly created array using newaxis function derived from arr_2
# See the new dimension added and has one more dimension than arr_2

arr_3.shape

(1, 5)

In [10]:
# Now we reverse the order of the two first making the number of elements and then the dimension

arr_4 = arr_2[:, np.newaxis]
arr_4

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [11]:
arr_4.shape

(5, 1)

In [12]:
# Create 2 more additional dimension with newaxis

arr_5 = arr_2[:, np.newaxis,np.newaxis]
arr_5

array([[[0]],

       [[1]],

       [[2]],

       [[3]],

       [[4]]])

In [13]:
arr_5.shape

(5, 1, 1)

---

#### Squeeze

In [14]:
# Remove the extra dimension

arr_6 = arr_5.squeeze()
arr_6.shape

(5,)

---

#### Transpose

In [15]:
arr_7 = np.arange(10)
arr_7.shape = 2,5
arr_7

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
# Transpose the array using the tranpose function

arr_7 = arr_7.transpose()
arr_7

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [17]:
# Transpose the array using the T function

arr_7.T

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

---

#### Concatenate

In [18]:
# Crate a new array

arr8 = np.arange(6)
arr8.shape = 2,3
arr8

array([[0, 1, 2],
       [3, 4, 5]])

In [19]:
# Create another array

arr9 = np.arange(41,100,10)
arr9 = arr9[np.newaxis,:]
arr9.shape = 2,3
arr9

array([[41, 51, 61],
       [71, 81, 91]])

In [20]:
# Concatenate both arrays
#Both can be concatenate since both have the same nth element (3 columns)

arr10 = np.concatenate((arr8, arr9))
arr10

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [41, 51, 61],
       [71, 81, 91]])

In [21]:
# Concatenate both arrays with axis =1

arr11 = np.concatenate((arr8, arr9), axis=1)
arr11

array([[ 0,  1,  2, 41, 51, 61],
       [ 3,  4,  5, 71, 81, 91]])

---

#### Vstack / Hstack

In [22]:
# Horizontal Stacking

np.vstack((arr8, arr9))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [41, 51, 61],
       [71, 81, 91]])

In [23]:
# Vertical Stacking

np.hstack((arr8, arr9))

array([[ 0,  1,  2, 41, 51, 61],
       [ 3,  4,  5, 71, 81, 91]])

---

#### Flatten

In [24]:
# Print arr10

arr10

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [41, 51, 61],
       [71, 81, 91]])

In [25]:
arr10.flatten()

array([ 0,  1,  2,  3,  4,  5, 41, 51, 61, 71, 81, 91])

---

#### Ravel

In [26]:
# Print arr10

arr10

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [41, 51, 61],
       [71, 81, 91]])

In [27]:
arr10.ravel()

array([ 0,  1,  2,  3,  4,  5, 41, 51, 61, 71, 81, 91])