### Numpy Functions to Create Arrays


---

#### Agenda:
 
   * Using **`` Arange ``** function to create array
   
   
   * Using **`` linspace ``** function to create array
   
   
   * Using **`` meshgrid ``** function to create a grid
    
  

---

In [2]:
import numpy as np

#### Create Array using Arange

In [3]:
# Create an array from 1 to 10 with interval of 1

arr_1 = np.arange(10)
arr_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# Create an array from 5 to 40 with interval of 5

arr_2 = np.arange(5,40,5)
arr_2

array([ 5, 10, 15, 20, 25, 30, 35])

In [6]:
# Create an array from 5 to 40 with interval of 5, with data type specified to float 32

np.arange(5,40,5, dtype=np.float32)

array([ 5., 10., 15., 20., 25., 30., 35.], dtype=float32)

---

> So let's suppose we have an exercise asking us to create 30 numbers from 0 to 10 unluckily resolving it with arange will not give us a result as its not possible. 


> Comes-in the linspace function

#### Using Linspace

In [8]:
# Allows us to create 20 equally stepped/scaled or equi-distance numbers from 0 to 10 

arr2 = np.linspace(0,10,20)
arr2

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

---

#### How to create a Grid?

In [10]:
#Create an array from -10 to 10 with 5 as equi-distance intervals

arr3 = np.linspace(-10,10,5)
arr3

array([-10.,  -5.,   0.,   5.,  10.])

In [11]:
# Create a second array

arr4 = np.linspace(-10,10,5)
arr4

array([-10.,  -5.,   0.,   5.,  10.])

In [12]:
# Create a grid

x ,y = np.meshgrid(arr3, arr4)

In [13]:
x

array([[-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.]])

In [14]:
y

array([[-10., -10., -10., -10., -10.],
       [ -5.,  -5.,  -5.,  -5.,  -5.],
       [  0.,   0.,   0.,   0.,   0.],
       [  5.,   5.,   5.,   5.,   5.],
       [ 10.,  10.,  10.,  10.,  10.]])