### Numpy Functions to Create Vector


---

#### Agenda:
 
   * Using **`` np.r_ ``** (row) function to create array
   
   
   * Using **`` np.c_ ``** (column) function to create array
   
   
   * Using **`` np.zeros ``** function to create an array of zeros
   
   
   * Using **`` np.ones ``** function to create an array of ones
   
   
   * Using **`` np.zeros_like ``** and **`` np.ones_like ``** function to create an array of ones
    
  

---

In [1]:
import numpy as np

#### Create Vector

In [2]:
# Create an array from 1 to 10 with interval of 1

# Row wise

arr_1 = np.r_[0:10:1]
arr_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# Create an array from 1 to 10 with interval of 1

# Column wise

arr_2 = np.c_[0:10:1]
arr_2

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [4]:
# Create an array of zeros

arr_3 = np.zeros(3)
arr_3

array([0., 0., 0.])

In [5]:
# Create a multi-dimensional array of zeros

arr_4 = np.zeros((5,6))
arr_4

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [6]:
# Create an array of zeros

arr_5 = np.ones((2,3))
arr_5

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
# Create an array of zeros

arr_6 = np.ones((2,3)) * 300
arr_6

array([[300., 300., 300.],
       [300., 300., 300.]])

In [8]:
np.ones((2,3), dtype=np.int32)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [9]:
# Copy the dimension of the array and fill it with zeros

np.zeros_like(arr_6)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
# Copy the dimension of the array and fill it with ones

np.ones_like(arr_6)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
# Create a matrix of zeros with only the diagonal are ones

np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])