### Random


---

#### Agenda:
 
   * Using **`` rand ``** operand to create random float numbers
   
   
   * Using **`` set_printoptions ``** ito set precision of decimal places
   
   
   * Using **`` randint ``** perand to create random interger numbers
   
   
   * Using **`` random.shuffle ``** to randomly shuffle the elements in the array
   
   
   * Using **`` seed ``** so that it will give the same ranom number and for reproducibility
   
    
  

---

In [1]:
import numpy as np

In [2]:
# Create a multi-dimensional array

np.random.rand(3,4)

array([[0.69177333, 0.00354538, 0.51314799, 0.34174242],
       [0.56328754, 0.32668433, 0.05908549, 0.85067294],
       [0.91799525, 0.66218441, 0.62075181, 0.71665176]])

In [3]:
# Set the decimal precision to 3

np.set_printoptions(precision=3)

In [4]:
# Check if if now use the 3 precision

np.random.rand(3,4)

array([[0.179, 0.228, 0.641, 0.024],
       [0.497, 0.431, 0.918, 0.183],
       [0.949, 0.488, 0.333, 0.758]])

In [5]:
# Create a random numbers from 0 to 29 and with 5x6 size.

np.random.randint(30, size = (5,6))

array([[ 1, 27, 12, 28, 13,  3],
       [15, 16, 17, 24, 11, 11],
       [18, 11, 10,  3,  2,  5],
       [10, 26,  1, 22,  5,  5],
       [ 3,  8, 28, 21, 21, 16]])

In [6]:
# Create 7 numbers from 0 to 29

np.random.randint(0,30,7)

array([10, 14, 16, 15, 28, 23, 21])

In [7]:
arr_1 = np.arange(100)
arr_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [8]:
np.random.shuffle(arr_1)

In [9]:
arr_1

array([77, 20, 80,  9, 42, 63, 90, 49, 81, 30,  5, 44, 16, 76,  6, 70, 96,
       94, 34, 14, 89, 79,  7, 67, 82, 60,  8, 24, 72, 88, 69, 17, 86, 98,
       62, 41, 85, 54, 78, 26, 58, 61, 68, 91, 95,  3, 23, 83, 74, 87, 51,
        0, 31, 73, 22, 93, 39, 99, 38, 92, 71, 97, 27, 37,  2, 48, 40, 11,
       53, 10, 55, 12, 36, 47,  1, 75, 45, 43, 15, 33, 13, 25, 46, 56,  4,
       50, 32, 84, 52, 21, 65, 19, 66, 59, 29, 18, 35, 57, 64, 28])

In [10]:
# Use of seed

np.random.seed(2)

In [11]:
np.random.rand(3,3)

array([[0.436, 0.026, 0.55 ],
       [0.435, 0.42 , 0.33 ],
       [0.205, 0.619, 0.3  ]])