### Numpy Logical Operations


---

#### Agenda:
 
   * Using **`` == ``** equal opeator
   
   
   * Using **`` != ``** is not equal opeator
   
   
   * Using **`` >= ``** greater than or equal opeator
   
   
   * Using **`` <= ``** less than or equal opeator
   
   
    
  

---

In [1]:
import numpy as np

In [2]:
# Create an array
# Compare both array to an equal operator
# Sizes should be the same

arr_1 = np.array([1,1,1,1])
arr_2 = np.array([1,1,1,8])

arr_1 == arr_2

array([ True,  True,  True, False])

In [3]:
# If sizes not the same

arr_3 = np.array([1,1,1,1,2])
arr_4 = np.array([1,1,1,8])

arr_3 == arr_4

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  


False

In [4]:
# Not equals

arr_1 != arr_2

array([False, False, False,  True])

In [5]:
# Greater than or Equal

arr_1 >= arr_2

array([ True,  True,  True, False])

In [6]:
# Less than or Equal

arr_1 <= arr_2

array([ True,  True,  True,  True])